# Generated by Django 5.0.6 on 2024-06-29 15:21

import loader.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(
                upload_to="documents/",
                validators=[loader.validators.validate_file_extension],
            ),
        ),
    ]
