# Generated by Django 5.0.6 on 2024-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loader", "0002_alter_document_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="row_count",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
