# Generated by Django 5.0.6 on 2024-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loader", "0003_document_row_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="transform_query",
            field=models.TextField(blank=True, default=""),
        ),
    ]
