# Generated by Django 5.0.6 on 2024-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loader", "0004_document_transform_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
